name: flutter_homework
description: Flutter Exercises

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.2.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/Math.png
